# Generated by Django 6.0.2 on 2026-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
